import { getFirestore } from 'firebase-admin/firestore'
import { onRequest } from 'firebase-functions/v2/https'
import { defineSecret } from 'firebase-functions/params'
import Stripe from 'stripe'
import { stripeSecretKey } from './stripeCheckout'
export const stripeWebhookSecret = defineSecret('STRIPE_WEBHOOK_SECRET')
export interface StripeWebhookEvent { type: string; clientReferenceId?: string; stripeSessionId?: string }
export const handleStripeWebhookEvent = async (deps: { getBillingRecord: (orgId: string, recordId: string) => Promise<{ status: string } | null>; markBillingRecordPaid: (orgId: string, recordId: string, session: string) => Promise<void> }, event: StripeWebhookEvent): Promise<void> => { if (event.type !== 'checkout.session.completed' || !event.clientReferenceId || !event.stripeSessionId) return; const i = event.clientReferenceId.indexOf(':'); if (i < 1 || i === event.clientReferenceId.length - 1) return; const orgId = event.clientReferenceId.slice(0, i), recordId = event.clientReferenceId.slice(i + 1); const record = await deps.getBillingRecord(orgId, recordId); if (!record || record.status === 'PAID') return; await deps.markBillingRecordPaid(orgId, recordId, event.stripeSessionId) }
export const stripeWebhookCallable = onRequest({ region: 'asia-northeast1', secrets: [stripeWebhookSecret, stripeSecretKey] }, async (request, response) => { const signature = request.headers['stripe-signature']; if (typeof signature !== 'string') { response.status(400).send('Missing signature'); return }; let event: Stripe.Event; try { event = new Stripe(stripeSecretKey.value()).webhooks.constructEvent(request.rawBody, signature, stripeWebhookSecret.value()) } catch { response.status(400).send('Invalid signature'); return }; const db = getFirestore(), session = event.data.object as Stripe.Checkout.Session; await handleStripeWebhookEvent({ getBillingRecord: async (o, r) => { const snap = await db.doc(`organizations/${o}/billingRecords/${r}`).get(); return snap.exists ? snap.data() as { status: string } : null }, markBillingRecordPaid: async (o, r, s) => { await db.doc(`organizations/${o}/billingRecords/${r}`).update({ status: 'PAID', paidAt: new Date().toISOString(), stripeSessionId: s }) } }, { type: event.type, clientReferenceId: session.client_reference_id ?? undefined, stripeSessionId: session.id }); response.status(200).send('ok') })
