import { useEffect, useRef, useState } from 'react'
import { onValue, ref } from 'firebase/database'
import { bootstrapFirebase } from '../../lib/firebase/bootstrap'
import { getOrCreateStudentUid } from '../../lib/auth/studentAuth'
import { armJoinRequestPresence, RECOVERY_CODE_LENGTH, requestToJoinMarket, resolveJoinCode } from '../../lib/market/marketRepository'
import { getStudentSessionId, readActiveStudentSession, saveActiveStudentSession } from '../../lib/students/studentSession'
import { useDatabaseConnected } from '../../lib/firebase/connectionState'
import { handleFailure } from '../../lib/monitoring/describeError'
import { Alert, Box, Button, Stack, Typography } from '@mui/material'
import { StudentField, StudentPageSurface, StudentSurfaceCard } from '../ui/StudentUi'
import { studentPrimaryActionSx } from '../ui/studentUiStyles'

export const StudentMarketJoin = () => {
  const services = bootstrapFirebase()
  const [joinCode, setJoinCode] = useState(() => new URLSearchParams(window.location.search).get('code')?.toUpperCase() ?? ''), [displayName, setDisplayName] = useState(''), [recoveryCode, setRecoveryCode] = useState(''), [marketId, setMarketId] = useState(''), [requestId, setRequestId] = useState('')
  const [status, setStatus] = useState<'entry' | 'requesting' | 'waiting' | 'approved' | 'error'>('entry'), [message, setMessage] = useState('参加コードを入力して、先生の市場に参加しましょう。')
  const activeSession = readActiveStudentSession()
  const presentedRecoveryCodeRef = useRef('')
  const connected = useDatabaseConnected(services.database)
  useEffect(() => { if (!marketId || !requestId) return; const stop = onValue(ref(services.database, `liveMarkets/${marketId}/joinRequests/${requestId}`), (snapshot) => { if (snapshot.val()?.approvedAtMillis) { const active = { marketId, requestId, sessionId: getStudentSessionId(), ...(presentedRecoveryCodeRef.current ? { presentedRecoveryCode: presentedRecoveryCodeRef.current } : {}) }; saveActiveStudentSession(active); setStatus('approved'); setMessage('参加が承認されました。市場画面へ移動します。'); window.location.assign(`/markets/${marketId}/play`) } }); return () => stop() }, [marketId, requestId, services.database])
  // The onDisconnect handler armed at request time does not survive a reconnect, so a
  // waiting student whose screen locks twice would flip connected back to true once but
  // then never again — vanishing from the teacher's admission panel on the second drop.
  // Re-arming on every reconnection, exactly as StudentMarketPage's matching effect does
  // for approved participants via armApprovedParticipantPresence, closes that gap too.
  useEffect(() => { if (status !== 'waiting' || !marketId || !requestId || !connected) return; void armJoinRequestPresence(services.database, marketId, requestId).catch((error) => setMessage(handleFailure(error, '接続状態を更新できませんでした。'))) }, [connected, marketId, requestId, services.database, status])
  const join = async () => { if (!joinCode.trim() || !displayName.trim()) { setStatus('error'); return setMessage('参加コードと表示名を入力してください。') }; const normalizedRecoveryCode = recoveryCode.trim().toUpperCase(); if (normalizedRecoveryCode && normalizedRecoveryCode.length !== RECOVERY_CODE_LENGTH) { setStatus('error'); return setMessage(`復帰コードを確認してください。${RECOVERY_CODE_LENGTH}文字で入力してください。`) }; setStatus('requesting'); try { const uid = await getOrCreateStudentUid(services.auth); const resolved = await resolveJoinCode(services.firestore, joinCode); if (!resolved) throw new Error('NOT_FOUND'); presentedRecoveryCodeRef.current = normalizedRecoveryCode; const id = await requestToJoinMarket(services.database, resolved, { uid, sessionId: getStudentSessionId(), displayName: displayName.trim(), requestedTeamId: null, ...(normalizedRecoveryCode ? { recoveryCode: normalizedRecoveryCode } : {}) }); setMarketId(resolved); setRequestId(id); setStatus('waiting'); setMessage('参加を申請しました。先生の承認をお待ちください。') } catch (error) { setStatus('error'); setMessage(error instanceof Error && error.message === 'NOT_FOUND' ? '市場が見つかりません。参加コードを確認してください。' : handleFailure(error, 'この市場は参加受付を終了しているか、接続できません。')) } }
  const joining = status === 'waiting' || status === 'requesting'
  return <StudentPageSurface><Box sx={{ px: { xs: 2, sm: 4 }, py: 3 }}><Stack component="header" direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center', mb: { xs: 3, sm: 5 }, maxWidth: 1040, mx: 'auto' }}><Button component="a" href="/" color="inherit" sx={{ minHeight: 48, px: 1, fontWeight: 800 }}>Stock League Classroom</Button><Typography variant="overline" color="text.secondary">STUDENT ENTRY</Typography></Stack><Box sx={{ maxWidth: 460, mx: 'auto' }}><StudentSurfaceCard><Stack spacing={2.25} sx={{ p: { xs: 3, sm: 4 } }}><Typography variant="overline" color="text.secondary">JOIN A MARKET</Typography><Typography component="h1" variant="h4" sx={{ fontWeight: 800 }}>市場に参加</Typography><Typography color="text.secondary">先生から受け取った参加コードと、教室で使う表示名を入力してください。</Typography>{activeSession && <Button component="a" href={`/markets/${activeSession.marketId}/play`} color="inherit" variant="text" sx={{ alignSelf: 'flex-start', px: 0 }}>前回の市場へ戻る →</Button>}{status === 'approved' ? <Alert severity="success"><Typography variant="h6">参加準備ができました</Typography>{message}</Alert> : <><StudentField label="参加コード" value={joinCode} maxLength={6} placeholder="例: A1B2C3" onChange={(event) => setJoinCode(event.target.value.toUpperCase())} disabled={joining} /><StudentField label="表示名（本名は入力しないでください）" value={displayName} maxLength={20} placeholder="例: ナナシ" onChange={(event) => setDisplayName(event.target.value)} disabled={joining} /><StudentField label="復帰コード（任意）" value={recoveryCode} maxLength={4} placeholder="例: A1B2" helperText="前の端末に表示された4文字です。初参加なら空欄で構いません。使う場合は、表示名も前回と同じ文字で入力してください。" onChange={(event) => setRecoveryCode(event.target.value.toUpperCase())} disabled={joining} /><Button variant="contained" size="large" type="button" fullWidth onClick={() => void join()} disabled={joining} sx={studentPrimaryActionSx}>{status === 'requesting' ? '市場を確認中…' : status === 'waiting' ? '先生の承認を待っています' : '参加を申請する'}　→</Button><Alert severity={status === 'error' ? 'error' : 'info'} role="status">{message}</Alert></>}</Stack></StudentSurfaceCard><Typography component="footer" variant="body2" color="text.secondary" align="center" sx={{ display: 'block', mt: 3 }}>投資はシミュレーションです。実際のお金は使用しません。</Typography></Box></Box></StudentPageSurface>
}
